import { expect, test } from '@playwright/test';

test('staging comparison to hypothesis exact source smoke', async ({ page, request }) => {
  test.setTimeout(60_000);
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(`pageerror: ${error.message}`));
  page.on('console', (message) => { if (message.type() === 'error') errors.push(`console: ${message.text()}`); });
  const batchId = '51000000-0000-0000-0000-000000000002';
  const firstContentId = '51000000-0000-0000-0000-000000000101';
  const secondContentId = '51000000-0000-0000-0000-000000000102';
  const workspaceResponse = await request.get(`/api/workspace?batchId=${batchId}`);
  expect(workspaceResponse.status(), 'Existing staging server must have a configured canonical workspace; Playwright shell does not need DB credentials').toBe(200);
  await page.goto(`/?batchId=${batchId}`);
  const selection = page.getByRole('list', { name: 'Comparison content selection' });
  const panel = page.getByRole('region', { name: 'Evidence-backed working insight' });
  await selection.getByRole('button', { name: /Organic primary high/ }).click();
  await selection.getByRole('button', { name: /Organic primary tie A/ }).click();
  const comparisonResponse = page.waitForResponse((response) => new URL(response.url()).pathname === '/api/comparisons' && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Generate comparison' }).click();
  expect((await comparisonResponse).status()).toBe(201);
  await expect(page.getByRole('heading', { name: 'Controlled comparison' })).toBeVisible();
  const hypothesisResponse = page.waitForResponse((response) => new URL(response.url()).pathname === '/api/hypotheses' && response.request().method() === 'POST');
  await panel.getByRole('button', { name: 'Generate hypothesis', exact: true }).click();
  const created = await hypothesisResponse;
  expect(created.status()).toBe(201);
  const artifact = await created.json();
  await expect(panel.getByText(`Artifact ${artifact.id} · confidence ${artifact.confidence}`, { exact: true })).toBeVisible();
  await expect(panel.getByText('Uji berikutnya yang disarankan')).toBeVisible();
  const readback = await request.get(`/api/hypotheses?hypothesisId=${encodeURIComponent(artifact.id)}`);
  expect(readback.status()).toBe(200);
  expect((await readback.json()).id).toBe(artifact.id);
  const exactLink = panel.getByRole('link', { name: 'Buka sumber exact' }).first();
  await expect(exactLink).toBeVisible();
  const sourceUrl = new URL((await exactLink.getAttribute('href'))!, page.url());
  expect(sourceUrl.origin).toBe(new URL(page.url()).origin);
  expect(sourceUrl.searchParams.get('batchId')).toBe(batchId);
  expect([firstContentId, secondContentId]).toContain(sourceUrl.searchParams.get('contentId'));
  expect(sourceUrl.hash).toMatch(/^#(?:metric-snapshot|transcript-segment|video-frame|content-feature)-/);
  await exactLink.click();
  await expect(page).toHaveURL(sourceUrl.href);
  await expect(page.locator(sourceUrl.hash)).toBeVisible();
  expect(errors).toEqual([]);
});
